"""
Синтетический датасет для классификации расходов.
Содержит примеры транзакций на русском, английском и казахском языках.
"""

TRAINING_DATA = [
    # ════════════════════════════════════════════════════════════════════
    # FOOD — Продукты / Азық-түлік
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Продукты Пятёрочка", "food"),
    ("Магнит продукты", "food"),
    ("ВкусВилл", "food"),
    ("Перекрёсток", "food"),
    ("Ашан гипермаркет", "food"),
    ("Лента супермаркет", "food"),
    ("Spar магазин", "food"),
    ("Дикси продукты", "food"),
    ("Metro cash carry продукты", "food"),
    ("Продуктовый магазин", "food"),
    ("Овощи фрукты", "food"),
    ("Молоко хлеб яйца", "food"),
    ("Пятёрочка", "food"),
    ("Магнит", "food"),
    ("Красное белое алкоголь", "food"),
    ("Вино магазин", "food"),
    ("Фермерские продукты", "food"),
    ("Рынок овощи", "food"),
    ("Окей гипермаркет", "food"),
    ("Семья маркет", "food"),
    ("Мясо магазин", "food"),
    ("Рыба свежая", "food"),
    ("Молочные продукты", "food"),
    ("Хлебобулочные изделия", "food"),
    ("Замороженные продукты", "food"),
    ("Консервы магазин", "food"),
    ("Колбаса деликатесы", "food"),
    ("Сыр молоко магазин", "food"),
    ("Детское питание", "food"),
    ("Кондитерская выпечка", "food"),
    ("Продуктовая корзина", "food"),
    ("Зелень специи", "food"),
    ("Бакалея", "food"),
    ("Супермаркет доставка", "food"),
    ("Сберфуд продукты", "food"),

    # English
    ("Grocery store", "food"),
    ("Supermarket", "food"),
    ("Walmart groceries", "food"),
    ("Whole Foods", "food"),
    ("Trader Joe's", "food"),
    ("Lidl lebensmittel", "food"),
    ("Aldi einkauf", "food"),
    ("Fresh market", "food"),
    ("Carrefour", "food"),
    ("Billa supermarkt", "food"),
    ("Costco groceries", "food"),
    ("Target food", "food"),
    ("Safeway groceries", "food"),
    ("Kroger supermarket", "food"),
    ("Publix store", "food"),
    ("Sprouts market", "food"),
    ("Organic food store", "food"),
    ("Farmers market produce", "food"),
    ("Bread and milk", "food"),
    ("Grocery delivery", "food"),
    ("FreshDirect order", "food"),
    ("Instacart groceries", "food"),
    ("H-E-B market", "food"),
    ("Meat shop", "food"),
    ("Dairy products store", "food"),
    ("Frozen food purchase", "food"),

    # Kazakh
    ("Азық-түлік дүкені", "food"),
    ("Нарық", "food"),
    ("Сүт нан жұмыртқа", "food"),
    ("Жаңа жемістер", "food"),
    ("Ет дүкені", "food"),
    ("Бауырсақ", "food"),
    ("Балық дүкені", "food"),
    ("Базар", "food"),
    ("Шаруа нарығы", "food"),
    ("Тамақ өнімдері", "food"),
    ("Көкөніс жемістер", "food"),
    ("Сүт өнімдері", "food"),
    ("Нан өнімдері", "food"),
    ("Ет өнімдері базар", "food"),
    ("Азық-түлік жеткізу", "food"),
    ("Дүкен тауарлары", "food"),

    # ════════════════════════════════════════════════════════════════════
    # CAFE — Кафе и рестораны / Мейрамханалар
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Кофе Старбакс", "cafe"),
    ("Макдоналдс", "cafe"),
    ("KFC", "cafe"),
    ("Бургер Кинг", "cafe"),
    ("Кофейня", "cafe"),
    ("Ресторан", "cafe"),
    ("Пиццерия", "cafe"),
    ("Суши ресторан", "cafe"),
    ("Pizza Hut", "cafe"),
    ("Dominos Pizza", "cafe"),
    ("Обед в кафе", "cafe"),
    ("Ланч бизнес", "cafe"),
    ("Завтрак кафе", "cafe"),
    ("Яндекс Еда доставка", "cafe"),
    ("Delivery Club еда", "cafe"),
    ("Wolt доставка", "cafe"),
    ("Еда навынос", "cafe"),
    ("Шаурма", "cafe"),
    ("Роллы суши заказ", "cafe"),
    ("Блинная кафе", "cafe"),
    ("Бар паб", "cafe"),
    ("Шашлычная", "cafe"),
    ("Столовая", "cafe"),
    ("Суши-бар", "cafe"),
    ("Буфет еда", "cafe"),
    ("Пирожковая", "cafe"),
    ("Чебуречная", "cafe"),
    ("Пельменная кафе", "cafe"),
    ("Бистро обед", "cafe"),
    ("Фудкорт ТЦ", "cafe"),
    ("Японский ресторан", "cafe"),
    ("Грузинский ресторан", "cafe"),
    ("Итальянский ресторан", "cafe"),
    ("Китайский ресторан", "cafe"),
    ("Кафе завтрак", "cafe"),

    # English
    ("Starbucks coffee", "cafe"),
    ("McDonald's", "cafe"),
    ("Burger King", "cafe"),
    ("Coffee shop", "cafe"),
    ("Restaurant dinner", "cafe"),
    ("Lunch cafe", "cafe"),
    ("Uber Eats", "cafe"),
    ("Fast food", "cafe"),
    ("Takeaway lunch", "cafe"),
    ("Sushi delivery", "cafe"),
    ("Pizza delivery", "cafe"),
    ("Coffee latte", "cafe"),
    ("Cappuccino", "cafe"),
    ("DoorDash order", "cafe"),
    ("Grubhub delivery", "cafe"),
    ("Just Eat delivery", "cafe"),
    ("Deliveroo order", "cafe"),
    ("Restaurant bill", "cafe"),
    ("Diner breakfast", "cafe"),
    ("Bar and grill", "cafe"),
    ("Sushi bar", "cafe"),
    ("Food court", "cafe"),
    ("Bistro lunch", "cafe"),
    ("Brunch restaurant", "cafe"),
    ("Thai restaurant", "cafe"),
    ("Mexican restaurant", "cafe"),

    # Kazakh
    ("Мейрамхана", "cafe"),
    ("Кафе", "cafe"),
    ("Шаурма дүкені", "cafe"),
    ("Тамақ жеткізу", "cafe"),
    ("Пицца жеткізу", "cafe"),
    ("Кофе дүкені", "cafe"),
    ("Буфет", "cafe"),
    ("Асхана", "cafe"),
    ("Тез тамақ", "cafe"),
    ("Ресторан кешкі ас", "cafe"),
    ("Суши бар", "cafe"),
    ("Кофехана", "cafe"),
    ("Жылдам тамақ", "cafe"),
    ("Тамақ алу", "cafe"),
    ("Кафе ас", "cafe"),

    # ════════════════════════════════════════════════════════════════════
    # TRANSPORT — Транспорт / Көлік
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Яндекс Такси", "transport"),
    ("Uber поездка", "transport"),
    ("Метро", "transport"),
    ("Автобус", "transport"),
    ("Электричка", "transport"),
    ("РЖД билет", "transport"),
    ("Авиабилет S7", "transport"),
    ("Аэрофлот", "transport"),
    ("Бензин АЗС", "transport"),
    ("Заправка Лукойл", "transport"),
    ("Парковка", "transport"),
    ("Самокат аренда", "transport"),
    ("Яндекс Go", "transport"),
    ("Каршеринг Делимобиль", "transport"),
    ("Автозаправка", "transport"),
    ("Shell бензин", "transport"),
    ("BP заправка", "transport"),
    ("Ласточка поезд", "transport"),
    ("Сапсан билет", "transport"),
    ("Такси", "transport"),
    ("Трамвай", "transport"),
    ("Троллейбус", "transport"),
    ("Маршрутка", "transport"),
    ("Автостоянка", "transport"),
    ("Мойка машины", "transport"),
    ("Техобслуживание авто", "transport"),
    ("Страховка авто ОСАГО", "transport"),
    ("Шиномонтаж", "transport"),
    ("Транспортная карта", "transport"),
    ("Аэроэкспресс", "transport"),
    ("Ситимобил", "transport"),
    ("Яндекс Драйв", "transport"),
    ("Каршеринг", "transport"),
    ("Велосипед аренда", "transport"),

    # English
    ("Taxi ride", "transport"),
    ("Uber trip", "transport"),
    ("Metro transit", "transport"),
    ("Bus ticket", "transport"),
    ("Train ticket", "transport"),
    ("Flight ticket", "transport"),
    ("Gas station fuel", "transport"),
    ("Parking fee", "transport"),
    ("Subway card", "transport"),
    ("Electric scooter rental", "transport"),
    ("Lyft ride", "transport"),
    ("Bolt taxi", "transport"),
    ("City bike rental", "transport"),
    ("Scooter Bird", "transport"),
    ("Grab taxi", "transport"),
    ("Car wash", "transport"),
    ("Vehicle maintenance", "transport"),
    ("Auto insurance", "transport"),
    ("Toll road payment", "transport"),
    ("Car rental", "transport"),
    ("Zipcar rental", "transport"),
    ("Oil change service", "transport"),
    ("Airport transfer", "transport"),
    ("Subway pass", "transport"),
    ("Monthly bus pass", "transport"),

    # Kazakh
    ("Такси", "transport"),
    ("Автобус билеті", "transport"),
    ("Метро", "transport"),
    ("Жанармай", "transport"),
    ("Паркинг", "transport"),
    ("Самокат жалдау", "transport"),
    ("Пойыз билеті", "transport"),
    ("Ұшақ билеті", "transport"),
    ("Маршруттық такси", "transport"),
    ("Көлік жуу", "transport"),
    ("Көлік жөндеу", "transport"),
    ("Бензин құю", "transport"),
    ("Велосипед жалдау", "transport"),
    ("Темір жол билеті", "transport"),
    ("Транспорт картасы", "transport"),

    # ════════════════════════════════════════════════════════════════════
    # HEALTH — Здоровье / Денсаулық
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Аптека", "health"),
    ("Лекарства", "health"),
    ("Врач консультация", "health"),
    ("Поликлиника", "health"),
    ("Стоматолог", "health"),
    ("Анализы лаборатория", "health"),
    ("Инвитро анализы", "health"),
    ("Спортзал абонемент", "health"),
    ("Фитнес клуб", "health"),
    ("Витамины БАД", "health"),
    ("Медицинская страховка", "health"),
    ("Йога студия", "health"),
    ("Бассейн абонемент", "health"),
    ("Медкомиссия", "health"),
    ("Поликлиника платная", "health"),
    ("Оптика очки", "health"),
    ("Контактные линзы", "health"),
    ("Массаж", "health"),
    ("Психолог сессия", "health"),
    ("Скорая помощь", "health"),
    ("УЗИ обследование", "health"),
    ("МРТ сканирование", "health"),
    ("Рентген", "health"),
    ("Терапевт", "health"),
    ("Педиатр", "health"),
    ("Невролог", "health"),
    ("Кардиолог", "health"),
    ("Офтальмолог", "health"),
    ("Косметолог", "health"),
    ("Аптека интернет", "health"),
    ("Гинеколог", "health"),
    ("Диетолог", "health"),

    # English
    ("Gym membership", "health"),
    ("Pharmacy", "health"),
    ("Doctor visit", "health"),
    ("Dentist", "health"),
    ("Medical checkup", "health"),
    ("Lab tests", "health"),
    ("Sports club", "health"),
    ("Physiotherapy", "health"),
    ("Vitamins supplement", "health"),
    ("Running shoes sport", "health"),
    ("Protein supplement", "health"),
    ("Emergency room", "health"),
    ("MRI scan", "health"),
    ("X-ray", "health"),
    ("Chiropractor", "health"),
    ("Health insurance", "health"),
    ("Eye glasses", "health"),
    ("Contact lenses", "health"),
    ("Blood test", "health"),
    ("Yoga class", "health"),
    ("Swimming pool membership", "health"),
    ("Personal trainer", "health"),
    ("Massage therapy", "health"),
    ("Psychotherapy session", "health"),
    ("Prescription medicine", "health"),

    # Kazakh
    ("Дәрі", "health"),
    ("Дәрігер", "health"),
    ("Стоматолог", "health"),
    ("Спорт залы", "health"),
    ("Витаминдер", "health"),
    ("Емхана", "health"),
    ("Медициналық тексеру", "health"),
    ("Психолог сеансы", "health"),
    ("Массаж", "health"),
    ("Дене шынықтыру клубы", "health"),
    ("Дәріхана", "health"),
    ("Зертхана талдауы", "health"),
    ("Йога студиясы", "health"),
    ("Бассейн абонементі", "health"),
    ("Медициналық сақтандыру", "health"),
    ("Тіс дәрігері", "health"),

    # ════════════════════════════════════════════════════════════════════
    # ENTERTAINMENT — Развлечения / Ойын-сауық
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Кино", "entertainment"),
    ("Кинотеатр", "entertainment"),
    ("Театр билет", "entertainment"),
    ("Концерт", "entertainment"),
    ("Netflix подписка", "entertainment"),
    ("Spotify музыка", "entertainment"),
    ("Игры Steam", "entertainment"),
    ("PlayStation Store", "entertainment"),
    ("Клуб ночной", "entertainment"),
    ("Боулинг", "entertainment"),
    ("Кино билет", "entertainment"),
    ("Квест комната", "entertainment"),
    ("YouTube Premium", "entertainment"),
    ("Apple Music", "entertainment"),
    ("Кинопоиск подписка", "entertainment"),
    ("Twitch подписка", "entertainment"),
    ("Disney+ подписка", "entertainment"),
    ("HBO Max", "entertainment"),
    ("Игровая приставка", "entertainment"),
    ("Nintendo Switch игра", "entertainment"),
    ("Аттракцион парк", "entertainment"),
    ("Зоопарк билет", "entertainment"),
    ("VK музыка", "entertainment"),
    ("Яндекс Музыка", "entertainment"),
    ("Литрес книги", "entertainment"),
    ("MyBook подписка", "entertainment"),
    ("Иви фильмы", "entertainment"),
    ("Okko стриминг", "entertainment"),
    ("Zoopark", "entertainment"),
    ("Цирк билет", "entertainment"),
    ("Аквапарк", "entertainment"),
    ("Картинг", "entertainment"),
    ("Лазертаг", "entertainment"),
    ("Бильярд", "entertainment"),

    # English
    ("Cinema ticket", "entertainment"),
    ("Movie theater", "entertainment"),
    ("Netflix subscription", "entertainment"),
    ("Spotify premium", "entertainment"),
    ("Steam games", "entertainment"),
    ("Concert ticket", "entertainment"),
    ("Museum", "entertainment"),
    ("Amusement park", "entertainment"),
    ("Escape room", "entertainment"),
    ("Board game", "entertainment"),
    ("Hulu streaming", "entertainment"),
    ("Prime Video subscription", "entertainment"),
    ("Apple TV+ subscription", "entertainment"),
    ("Twitch channel subscription", "entertainment"),
    ("Audible audiobook", "entertainment"),
    ("Kindle books", "entertainment"),
    ("IMAX movie", "entertainment"),
    ("VR experience", "entertainment"),
    ("Laser tag", "entertainment"),
    ("Mini golf", "entertainment"),
    ("Theme park ticket", "entertainment"),
    ("Zoo ticket", "entertainment"),
    ("Bowling night", "entertainment"),
    ("Night club", "entertainment"),
    ("Comedy show ticket", "entertainment"),

    # Kazakh
    ("Кино билеті", "entertainment"),
    ("Театр", "entertainment"),
    ("Netflix жазылым", "entertainment"),
    ("Ойындар", "entertainment"),
    ("Концерт билеті", "entertainment"),
    ("Мұражай", "entertainment"),
    ("Аквапарк", "entertainment"),
    ("Зоопарк", "entertainment"),
    ("Ойын-сауық орталығы", "entertainment"),
    ("Квест бөлмесі", "entertainment"),
    ("Боулинг", "entertainment"),
    ("Лазертаг", "entertainment"),
    ("Ойын приставкасы", "entertainment"),
    ("Музыка жазылым", "entertainment"),
    ("Цирк билеті", "entertainment"),

    # ════════════════════════════════════════════════════════════════════
    # UTILITIES — Коммунальные услуги / Коммуналдық қызметтер
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Квартплата ЖКХ", "utilities"),
    ("Электричество", "utilities"),
    ("Газ", "utilities"),
    ("Вода", "utilities"),
    ("Интернет провайдер", "utilities"),
    ("Мобильная связь МТС", "utilities"),
    ("Билайн тариф", "utilities"),
    ("Мегафон", "utilities"),
    ("Коммунальные платежи", "utilities"),
    ("Домофон обслуживание", "utilities"),
    ("Аренда квартиры", "utilities"),
    ("Платёж по ипотеке", "utilities"),
    ("Домашний интернет", "utilities"),
    ("Кабельное ТВ", "utilities"),
    ("Теплоснабжение", "utilities"),
    ("Вывоз мусора", "utilities"),
    ("Капитальный ремонт", "utilities"),
    ("Страховка квартиры", "utilities"),
    ("Управляющая компания", "utilities"),
    ("Tele2 связь", "utilities"),
    ("Yota тариф", "utilities"),
    ("Ростелеком", "utilities"),
    ("Водоканал", "utilities"),
    ("Теплосеть", "utilities"),
    ("Газпром межрегионгаз", "utilities"),
    ("Охрана дома", "utilities"),
    ("Уборка квартиры", "utilities"),

    # English
    ("Rent payment", "utilities"),
    ("Electricity bill", "utilities"),
    ("Gas bill", "utilities"),
    ("Water bill", "utilities"),
    ("Internet subscription", "utilities"),
    ("Mobile phone plan", "utilities"),
    ("Housing utilities", "utilities"),
    ("Home insurance", "utilities"),
    ("Electric bill", "utilities"),
    ("Water utility", "utilities"),
    ("Cable TV subscription", "utilities"),
    ("Renters insurance", "utilities"),
    ("Property insurance", "utilities"),
    ("Homeowner association fee", "utilities"),
    ("Cleaning service", "utilities"),
    ("Security system", "utilities"),
    ("Streaming bundle", "utilities"),
    ("Phone plan", "utilities"),
    ("Broadband internet", "utilities"),
    ("Trash collection", "utilities"),
    ("Heating bill", "utilities"),
    ("Power bill", "utilities"),
    ("Mortgage payment", "utilities"),

    # Kazakh
    ("Коммуналдық төлем", "utilities"),
    ("Электр энергиясы", "utilities"),
    ("Газ төлемі", "utilities"),
    ("Су төлемі", "utilities"),
    ("Интернет", "utilities"),
    ("Ұялы байланыс", "utilities"),
    ("Жалдау ақы", "utilities"),
    ("Жылыту", "utilities"),
    ("Қоқыс шығару", "utilities"),
    ("Үй сақтандыруы", "utilities"),
    ("Кабельді ТВ", "utilities"),
    ("Ипотека төлемі", "utilities"),
    ("ЖКХ төлемі", "utilities"),
    ("Тұрмыстық қызметтер", "utilities"),

    # ════════════════════════════════════════════════════════════════════
    # SHOPPING — Покупки / Сатып алу
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Zara одежда", "shopping"),
    ("H&M", "shopping"),
    ("Wildberries покупка", "shopping"),
    ("Ozon заказ", "shopping"),
    ("IKEA мебель", "shopping"),
    ("Leroy Merlin", "shopping"),
    ("DNS электроника", "shopping"),
    ("М.Видео", "shopping"),
    ("Эльдорадо техника", "shopping"),
    ("Adidas кроссовки", "shopping"),
    ("Nike магазин", "shopping"),
    ("Обувь магазин", "shopping"),
    ("Книги", "shopping"),
    ("Книжный магазин", "shopping"),
    ("Decathlon спорт", "shopping"),
    ("Спортмастер", "shopping"),
    ("Детские товары", "shopping"),
    ("Игрушки ребёнку", "shopping"),
    ("Косметика Л'Этуаль", "shopping"),
    ("Рив Гош парфюм", "shopping"),
    ("Apple Store", "shopping"),
    ("Samsung телефон", "shopping"),
    ("Мебель диван", "shopping"),
    ("Посуда кухня", "shopping"),
    ("Алиэкспресс заказ", "shopping"),
    ("Яндекс Маркет", "shopping"),
    ("СберМегаМаркет", "shopping"),
    ("Авито покупка", "shopping"),
    ("Ювелирный магазин", "shopping"),
    ("Товары для дома", "shopping"),
    ("Строительные материалы", "shopping"),
    ("Автозапчасти", "shopping"),
    ("Зоомагазин", "shopping"),
    ("Канцтовары", "shopping"),
    ("Подарки магазин", "shopping"),
    ("Цветочный магазин", "shopping"),

    # English
    ("Amazon order", "shopping"),
    ("Clothing store", "shopping"),
    ("Online shopping", "shopping"),
    ("Electronics purchase", "shopping"),
    ("Furniture store", "shopping"),
    ("Department store", "shopping"),
    ("eBay purchase", "shopping"),
    ("Etsy shop", "shopping"),
    ("Best Buy electronics", "shopping"),
    ("Home Depot", "shopping"),
    ("Walmart online", "shopping"),
    ("Target purchase", "shopping"),
    ("Costco membership", "shopping"),
    ("Jewelry store", "shopping"),
    ("Gift shop", "shopping"),
    ("Pet store", "shopping"),
    ("Office supplies", "shopping"),
    ("Shopify store", "shopping"),
    ("Sports equipment", "shopping"),
    ("Toy store", "shopping"),
    ("Beauty store", "shopping"),
    ("Cosmetics purchase", "shopping"),
    ("Phone purchase", "shopping"),
    ("Laptop purchase", "shopping"),

    # Kazakh
    ("Киім дүкені", "shopping"),
    ("Онлайн сатып алу", "shopping"),
    ("Электроника", "shopping"),
    ("Жиһаз", "shopping"),
    ("Аяқ киім", "shopping"),
    ("Косметика", "shopping"),
    ("Кітаптар", "shopping"),
    ("Зергерлік бұйымдар", "shopping"),
    ("Спорт тауарлары", "shopping"),
    ("Үй тауарлары", "shopping"),
    ("Балаларға ойыншықтар", "shopping"),
    ("Телефон сатып алу", "shopping"),
    ("Интернет дүкен", "shopping"),
    ("Мата дүкені", "shopping"),
    ("Сыйлық дүкені", "shopping"),

    # ════════════════════════════════════════════════════════════════════
    # EDUCATION — Образование / Білім
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Курсы программирования", "education"),
    ("Coursera подписка", "education"),
    ("Udemy курс", "education"),
    ("Skillbox обучение", "education"),
    ("Яндекс Практикум", "education"),
    ("Репетитор", "education"),
    ("Школа английского", "education"),
    ("Учебники", "education"),
    ("Конференция", "education"),
    ("Подписка Medium", "education"),
    ("Вебинар", "education"),
    ("Мастер-класс", "education"),
    ("Khan Academy", "education"),
    ("Duolingo Plus", "education"),
    ("DataCamp", "education"),
    ("Университет взнос", "education"),
    ("Экзамен сертификат", "education"),
    ("Нетология курс", "education"),
    ("GeekBrains", "education"),
    ("OTUS обучение", "education"),
    ("Stepik курсы", "education"),
    ("Лекториум", "education"),
    ("Школа искусств", "education"),
    ("Музыкальная школа", "education"),
    ("Кружки секции", "education"),
    ("Учебные материалы", "education"),
    ("Подготовительные курсы", "education"),
    ("MBA программа", "education"),
    ("Профессиональный сертификат", "education"),
    ("Онлайн школа", "education"),

    # English
    ("Online course", "education"),
    ("Coursera premium", "education"),
    ("Udemy course", "education"),
    ("Tutoring", "education"),
    ("Language school", "education"),
    ("University fee", "education"),
    ("Pluralsight subscription", "education"),
    ("Bookclub подписка", "education"),
    ("LinkedIn Learning", "education"),
    ("Codecademy", "education"),
    ("edX course", "education"),
    ("Bootcamp payment", "education"),
    ("Professional certification", "education"),
    ("Online workshop", "education"),
    ("Masterclass subscription", "education"),
    ("Skillshare subscription", "education"),
    ("Rosetta Stone", "education"),
    ("Textbooks purchase", "education"),
    ("School fee", "education"),
    ("Seminar registration", "education"),
    ("Training program", "education"),

    # Kazakh
    ("Онлайн курс", "education"),
    ("Репетитор", "education"),
    ("Ағылшын тілі мектебі", "education"),
    ("Университет төлемі", "education"),
    ("Кітаптар", "education"),
    ("Мектеп төлемі", "education"),
    ("Оқу материалдары", "education"),
    ("Семинар", "education"),
    ("Кәсіби сертификат", "education"),
    ("Тіл курстары", "education"),
    ("Оқу курсы", "education"),
    ("Вебинар", "education"),
    ("Мастер класс", "education"),
    ("Дарынды мектеп", "education"),
    ("Колледж төлемі", "education"),

    # ════════════════════════════════════════════════════════════════════
    # TRAVEL — Путешествия / Саяхат
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Отель бронь", "travel"),
    ("Гостиница", "travel"),
    ("Booking.com", "travel"),
    ("Airbnb аренда", "travel"),
    ("Туристическая путёвка", "travel"),
    ("Визовый сбор", "travel"),
    ("Экскурсия тур", "travel"),
    ("Санаторий отдых", "travel"),
    ("Hostel бронь", "travel"),
    ("Круиз", "travel"),
    ("Горнолыжный курорт", "travel"),
    ("Туристическая страховка", "travel"),
    ("Чемодан багаж", "travel"),
    ("Аренда авто путешествие", "travel"),
    ("Трансфер аэропорт", "travel"),
    ("Hotels.com бронь", "travel"),
    ("Trivago", "travel"),
    ("Ostrovok", "travel"),
    ("Авиасейлс", "travel"),
    ("Туроператор", "travel"),
    ("Пансионат", "travel"),
    ("Дача аренда отдых", "travel"),
    ("Кемпинг", "travel"),
    ("Глэмпинг", "travel"),
    ("Спа отель", "travel"),
    ("Апартаменты аренда", "travel"),
    ("Курорт путёвка", "travel"),

    # English
    ("Hotel booking", "travel"),
    ("Airbnb stay", "travel"),
    ("Tourist package", "travel"),
    ("Visa fee", "travel"),
    ("Travel insurance", "travel"),
    ("Resort hotel", "travel"),
    ("Vacation rental", "travel"),
    ("Expedia hotel", "travel"),
    ("Agoda booking", "travel"),
    ("Car rental travel", "travel"),
    ("Disney resort", "travel"),
    ("Beach resort", "travel"),
    ("Hostel reservation", "travel"),
    ("City tour", "travel"),
    ("Kayak flights", "travel"),
    ("Priceline hotel", "travel"),
    ("Cruise booking", "travel"),
    ("Ski resort", "travel"),
    ("Airport hotel", "travel"),
    ("Sightseeing tour", "travel"),

    # Kazakh
    ("Қонақ үй", "travel"),
    ("Брондау", "travel"),
    ("Туристік пакет", "travel"),
    ("Виза төлемі", "travel"),
    ("Саяхат сақтандыруы", "travel"),
    ("Курорт", "travel"),
    ("Жалдамалы пәтер", "travel"),
    ("Экскурсия", "travel"),
    ("Демалыс орны", "travel"),
    ("Саяхат турпакет", "travel"),
    ("Шетел сапары", "travel"),
    ("Демалыс брондау", "travel"),
    ("Туристік сақтандыру", "travel"),

    # ════════════════════════════════════════════════════════════════════
    # TRANSFER — Переводы / Аударым
    # ════════════════════════════════════════════════════════════════════

    # Russian
    ("Перевод другу", "transfer"),
    ("Перевод семье", "transfer"),
    ("Перевод Тинькофф", "transfer"),
    ("SBP перевод", "transfer"),
    ("Деньги родителям", "transfer"),
    ("Возврат долга", "transfer"),
    ("Оплата аренды перевод", "transfer"),
    ("Сбербанк перевод", "transfer"),
    ("ВТБ перевод", "transfer"),
    ("Альфа-банк перевод", "transfer"),
    ("Оплата другу", "transfer"),
    ("Долг возврат", "transfer"),
    ("Перевод брату", "transfer"),
    ("Тинькофф перевод", "transfer"),
    ("Пополнение карты", "transfer"),
    ("Погашение кредита", "transfer"),
    ("Возврат займа", "transfer"),
    ("Алименты", "transfer"),
    ("Страховой взнос", "transfer"),
    ("Налог ФНС", "transfer"),
    ("Штраф оплата", "transfer"),
    ("Перевод сестре", "transfer"),
    ("Банковский перевод", "transfer"),
    ("Деньги коллеге", "transfer"),
    ("Оплата услуг", "transfer"),

    # English
    ("Wire transfer", "transfer"),
    ("Bank transfer", "transfer"),
    ("Send money", "transfer"),
    ("PayPal transfer", "transfer"),
    ("Wise transfer", "transfer"),
    ("Venmo payment", "transfer"),
    ("Zelle send", "transfer"),
    ("MoneyGram transfer", "transfer"),
    ("Western Union", "transfer"),
    ("Revolut transfer", "transfer"),
    ("Cash App transfer", "transfer"),
    ("Chime transfer", "transfer"),
    ("Remittance", "transfer"),
    ("Money to family", "transfer"),
    ("Debt repayment", "transfer"),
    ("Loan repayment", "transfer"),
    ("Rent transfer", "transfer"),
    ("Friend payment", "transfer"),

    # Kazakh
    ("Досқа аудару", "transfer"),
    ("Отбасыға аудару", "transfer"),
    ("Банк аударымы", "transfer"),
    ("Ақша жіберу", "transfer"),
    ("Kaspi аударым", "transfer"),
    ("Халық банк аударым", "transfer"),
    ("Карта толықтыру", "transfer"),
    ("Қарыз қайтару", "transfer"),
    ("Алимент", "transfer"),
    ("Несие өтеу", "transfer"),
    ("Туысқанға аудару", "transfer"),
    ("Жалақы аудару", "transfer"),

    # ════════════════════════════════════════════════════════════════════
    # РАСШИРЕНИЕ — Шаг 2. Больше примеров, вариации, казахстанские бренды
    # ════════════════════════════════════════════════════════════════════

    # ── FOOD extended ────────────────────────────────────────────────────
    ("Пятак продукты", "food"),
    ("Супермаркет покупка", "food"),
    ("Продукты домой", "food"),
    ("Еда на неделю", "food"),
    ("Мясо говядина", "food"),
    ("Курица магазин", "food"),
    ("Рыба осётр", "food"),
    ("Хлеб батон", "food"),
    ("Яблоки апельсины", "food"),
    ("Кефир молоко", "food"),
    ("Гречка рис крупы", "food"),
    ("Масло растительное", "food"),
    ("Яйца дюжина", "food"),
    ("Сок напитки", "food"),
    ("Минеральная вода", "food"),
    ("Чай кофе магазин", "food"),
    ("Макароны спагетти", "food"),
    ("Сахар соль специи", "food"),
    ("Магазин у дома", "food"),
    ("Заказ продуктов онлайн", "food"),
    ("Grocery pickup", "food"),
    ("Organic groceries", "food"),
    ("Ethnic food market", "food"),
    ("Butcher shop", "food"),
    ("Fish market", "food"),
    ("Bakery bread", "food"),
    ("Dairy farm products", "food"),
    ("Weekly groceries", "food"),
    ("Food delivery groceries", "food"),
    ("Vegetable market", "food"),
    ("Мал еті дүкені", "food"),
    ("Сүт қаймақ", "food"),
    ("Шай кофе азық", "food"),
    ("Жаңа нан", "food"),
    ("Тауық еті", "food"),
    ("Балық базары", "food"),
    ("Жеміс жидектер", "food"),
    ("Күнделікті азық-түлік", "food"),
    ("Дүкен сатып алу", "food"),
    ("Тамақ тапсырысы", "food"),

    # ── FOOD extra: чёткие маркеры «магазин/супермаркет/рынок» ──────────
    ("Магнит покупки", "food"),
    ("Пятёрочка продукты", "food"),
    ("Перекрёсток супермаркет", "food"),
    ("Лента гипермаркет", "food"),
    ("ВкусВилл молочка", "food"),
    ("Дикси хлеб молоко", "food"),
    ("Рынок овощи фрукты", "food"),
    ("Базар мясо", "food"),
    ("Зелёный базар продукты", "food"),
    ("Арбуз дыня рынок", "food"),
    ("Супермаркет напитки", "food"),
    ("Бакалея специи", "food"),
    ("Продуктовый ларёк", "food"),
    ("Grocery store visit", "food"),
    ("Supermarket checkout", "food"),
    ("Farmers market produce", "food"),
    ("Convenience store snacks", "food"),
    ("Whole Foods groceries", "food"),
    ("Costco bulk food", "food"),
    ("Trader Joe's", "food"),
    ("Азық-түлік дүкені сатып алу", "food"),
    ("Нан сүт жұмыртқа", "food"),
    ("Ет базары", "food"),
    ("Көкөніс жемістер базары", "food"),
    ("Сарымсақ пияз дүкен", "food"),
    ("Магазин азық", "food"),
    ("Супермаркет өнімдер", "food"),
    ("Алматы жемісі", "food"),
    ("Дүкен азық-түлік", "food"),

    # ── CAFE extra: чёткие маркеры «ресторан/кафе/заведение» ────────────
    ("Кофе с собой", "cafe"),
    ("Бизнес ланч", "cafe"),
    ("Обед на работе", "cafe"),
    ("Ужин ресторан", "cafe"),
    ("Завтрак омлет", "cafe"),
    ("Чай пирожное", "cafe"),
    ("Десерт кафе", "cafe"),
    ("Банкет ресторан", "cafe"),
    ("День рождения кафе", "cafe"),
    ("Корпоратив ресторан", "cafe"),
    ("Сухой паёк еда", "cafe"),
    ("Снэки перекус", "cafe"),
    ("Донер шаурма", "cafe"),
    ("Плов столовая", "cafe"),
    ("Лагман кафе", "cafe"),
    ("Breakfast diner", "cafe"),
    ("Office lunch", "cafe"),
    ("Coffee to go", "cafe"),
    ("Team lunch cafe", "cafe"),
    ("Birthday dinner", "cafe"),
    ("Brunch spot", "cafe"),
    ("Happy hour bar", "cafe"),
    ("Afternoon tea", "cafe"),
    ("Tapas restaurant", "cafe"),
    ("Ramen shop", "cafe"),
    ("Korean BBQ", "cafe"),
    ("Indian restaurant", "cafe"),
    ("Vietnamese pho", "cafe"),
    ("Таңертеңгі ас кафе", "cafe"),
    ("Түскі ас мейрамхана", "cafe"),
    ("Кешкі ас ресторан", "cafe"),
    ("Кофе алу", "cafe"),
    ("Туған күн мейрамханасы", "cafe"),
    ("Плов дүкені", "cafe"),
    ("Самса", "cafe"),
    ("Лагман", "cafe"),
    ("Манты", "cafe"),
    ("Бешбармақ мейрамхана", "cafe"),
    ("Тамақ тапсырыс жеткізу", "cafe"),
    ("Шашлык мангал", "cafe"),
    ("Суши бар", "cafe"),
    ("Пицца ресторан", "cafe"),
    ("Бургер бар", "cafe"),
    ("Блинная", "cafe"),
    ("Пельменная", "cafe"),
    ("Шаурма точка", "cafe"),
    ("Кофейня завтрак", "cafe"),
    ("Бизнес-ланч", "cafe"),
    ("Ужин с друзьями ресторан", "cafe"),
    ("Hookah lounge", "cafe"),
    ("Sushi restaurant", "cafe"),
    ("Burger joint", "cafe"),
    ("Pizza delivery order", "cafe"),
    ("Fine dining restaurant", "cafe"),
    ("Coffee shop espresso", "cafe"),
    ("Pancake house", "cafe"),
    ("Taco truck", "cafe"),
    ("Мейрамхана кешкі ас", "cafe"),
    ("Пицца тапсырыс", "cafe"),
    ("Бургер жеу", "cafe"),
    ("Кофе кафе", "cafe"),
    ("Достармен кешкі ас", "cafe"),
    ("Шашлық мейрамхана", "cafe"),
    ("Фастфуд мейрамхана", "cafe"),
    ("Күнделікті кофе", "cafe"),
    ("Жеткізу тамақ", "cafe"),
    ("Піцца жеткізу", "cafe"),

    # ── TRANSPORT extended ────────────────────────────────────────────────
    ("Проездной транспорт", "transport"),
    ("Карта тройка", "transport"),
    ("Единый билет", "transport"),
    ("Ж/Д плацкарт", "transport"),
    ("Купе поезд", "transport"),
    ("Такси аэропорт", "transport"),
    ("Такси ночной", "transport"),
    ("Мотоцикл бензин", "transport"),
    ("Газ пропан автомобиль", "transport"),
    ("Автострахование", "transport"),
    ("ТО автосервис", "transport"),
    ("Автомойка", "transport"),
    ("Штраф ГИБДД", "transport"),
    ("Эвакуатор", "transport"),
    ("Ремонт авто", "transport"),
    ("Commuter train pass", "transport"),
    ("Weekly transit card", "transport"),
    ("Monthly metro pass", "transport"),
    ("Intercity bus", "transport"),
    ("Night bus ticket", "transport"),
    ("Fuel fill up", "transport"),
    ("Car service repair", "transport"),
    ("Traffic fine", "transport"),
    ("Road toll", "transport"),
    ("Bicycle repair", "transport"),
    ("Scooter charge", "transport"),
    ("Tram ticket", "transport"),
    ("Ferry ticket", "transport"),
    ("Маршруттық автобус", "transport"),
    ("Жол жүру билеті", "transport"),
    ("Ай сайынғы билет", "transport"),
    ("Таксиге отыру", "transport"),
    ("Жанармай толтыру", "transport"),
    ("Автомобиль жөндеу", "transport"),
    ("Машина жуу", "transport"),
    ("Тиын жол", "transport"),
    ("Поезд купе", "transport"),
    ("Транспорт айыппұлы", "transport"),
    ("Велосипед жөндеу", "transport"),

    # ── HEALTH extended ────────────────────────────────────────────────
    ("Диета питание", "health"),
    ("Пробежка абонемент", "health"),
    ("Спортивное питание", "health"),
    ("Беговые кроссовки", "health"),
    ("Велотренажёр", "health"),
    ("Гантели спорт", "health"),
    ("Медицинская маска", "health"),
    ("Термометр аптека", "health"),
    ("Бинт перевязка", "health"),
    ("Антибиотики", "health"),
    ("Капли глазные", "health"),
    ("Коронавирус тест", "health"),
    ("Онлайн врач", "health"),
    ("Санаторий лечение", "health"),
    ("Реабилитация", "health"),
    ("Annual physical exam", "health"),
    ("Health screening", "health"),
    ("Dental cleaning", "health"),
    ("Eye exam", "health"),
    ("Flu vaccine", "health"),
    ("Fitness tracker", "health"),
    ("Sports nutrition", "health"),
    ("Mental health therapy", "health"),
    ("Acupuncture", "health"),
    ("Online doctor", "health"),
    ("Medical scan", "health"),
    ("Skin care dermatologist", "health"),
    ("Orthopedic shoes", "health"),
    ("Dental braces", "health"),
    ("Hair treatment salon", "health"),
    ("Дене шынықтыру", "health"),
    ("Спорттық тамақтану", "health"),
    ("Онлайн дәрігер", "health"),
    ("Медициналық маска", "health"),
    ("Санаторий емдеу", "health"),
    ("Жүгіру абонементі", "health"),
    ("Диета тамағы", "health"),
    ("Тіс тазалау", "health"),
    ("Көз тексеру", "health"),
    ("Вакцина", "health"),

    # ── ENTERTAINMENT extended ────────────────────────────────────────────
    ("Подписка на игры", "entertainment"),
    ("Игровой PC сборка", "entertainment"),
    ("Наушники музыка", "entertainment"),
    ("Книга бумажная", "entertainment"),
    ("Настольная игра", "entertainment"),
    ("Пазл головоломка", "entertainment"),
    ("Аниме подписка", "entertainment"),
    ("Манга комикс", "entertainment"),
    ("Подкаст подписка", "entertainment"),
    ("VR очки", "entertainment"),
    ("Стриминг фильмы", "entertainment"),
    ("Электронная книга", "entertainment"),
    ("Рыбалка лицензия", "entertainment"),
    ("Охота разрешение", "entertainment"),
    ("Спортивный матч", "entertainment"),
    ("Sports game ticket", "entertainment"),
    ("Football match", "entertainment"),
    ("Basketball game", "entertainment"),
    ("Vinyl record", "entertainment"),
    ("Art gallery", "entertainment"),
    ("Photography club", "entertainment"),
    ("Dance class", "entertainment"),
    ("Cooking class", "entertainment"),
    ("Wine tasting", "entertainment"),
    ("Book club", "entertainment"),
    ("Podcast premium", "entertainment"),
    ("Digital comics", "entertainment"),
    ("Gaming headset", "entertainment"),
    ("Karaoke night", "entertainment"),
    ("Spa entertainment", "entertainment"),
    ("Футбол ойыны билеті", "entertainment"),
    ("Баскетбол матч", "entertainment"),
    ("Ән-би кеші", "entertainment"),
    ("Кітап оқу клубы", "entertainment"),
    ("Би сабағы", "entertainment"),
    ("Өнер галереясы", "entertainment"),
    ("Ойын клубы", "entertainment"),
    ("Спорт матч билеті", "entertainment"),
    ("Стриминг жазылым", "entertainment"),
    ("Электронды кітап", "entertainment"),

    # ── UTILITIES extended ────────────────────────────────────────────
    ("Платёж за ЖКУ", "utilities"),
    ("Квартплата декабрь", "utilities"),
    ("Свет вода газ", "utilities"),
    ("Техподдержка интернет", "utilities"),
    ("Роутер провайдер", "utilities"),
    ("Антивирус подписка", "utilities"),
    ("Облачное хранилище", "utilities"),
    ("Google One подписка", "utilities"),
    ("iCloud хранилище", "utilities"),
    ("Microsoft 365", "utilities"),
    ("VPN подписка", "utilities"),
    ("Домен сайт", "utilities"),
    ("Хостинг сервер", "utilities"),
    ("Электромобиль зарядка", "utilities"),
    ("Солнечная панель", "utilities"),
    ("Annual utility bill", "utilities"),
    ("Cloud storage plan", "utilities"),
    ("iCloud storage", "utilities"),
    ("Google storage", "utilities"),
    ("VPN service", "utilities"),
    ("Domain renewal", "utilities"),
    ("Web hosting", "utilities"),
    ("Electric car charging", "utilities"),
    ("Landline phone", "utilities"),
    ("Satellite TV", "utilities"),
    ("Fiber internet", "utilities"),
    ("Smart home subscription", "utilities"),
    ("Alarm system fee", "utilities"),
    ("Condo maintenance", "utilities"),
    ("Building maintenance", "utilities"),
    ("Коммуналдық желілер", "utilities"),
    ("Электр шоты", "utilities"),
    ("Газ шоты", "utilities"),
    ("Су шоты", "utilities"),
    ("Интернет жоспары", "utilities"),
    ("Бұлтты сақтау", "utilities"),
    ("VPN жазылым", "utilities"),
    ("Үй интернеті", "utilities"),
    ("Мобильді жоспар", "utilities"),
    ("Спутниктік ТВ", "utilities"),

    # ── SHOPPING extended ────────────────────────────────────────────
    ("Шопинг молл", "shopping"),
    ("ТЦ покупки", "shopping"),
    ("Распродажа скидки", "shopping"),
    ("Чёрная пятница", "shopping"),
    ("Интернет заказ", "shopping"),
    ("Доставка посылка", "shopping"),
    ("Пункт выдачи", "shopping"),
    ("Возврат товара", "shopping"),
    ("Подарочный сертификат", "shopping"),
    ("Бытовая химия", "shopping"),
    ("Стиральный порошок", "shopping"),
    ("Средства гигиены", "shopping"),
    ("Шампунь гель", "shopping"),
    ("Духи парфюм", "shopping"),
    ("Аксессуары сумка", "shopping"),
    ("Black Friday deal", "shopping"),
    ("Cyber Monday sale", "shopping"),
    ("Flash sale purchase", "shopping"),
    ("Gift card purchase", "shopping"),
    ("Household supplies", "shopping"),
    ("Cleaning products", "shopping"),
    ("Personal hygiene", "shopping"),
    ("Perfume fragrance", "shopping"),
    ("Handbag accessory", "shopping"),
    ("Watch purchase", "shopping"),
    ("Sunglasses store", "shopping"),
    ("Hardware store", "shopping"),
    ("Garden supplies", "shopping"),
    ("Baby clothes", "shopping"),
    ("School supplies", "shopping"),
    ("Сауда орталығы", "shopping"),
    ("Онлайн тапсырыс", "shopping"),
    ("Жеңілдік сатып алу", "shopping"),
    ("Тұрмыстық химия", "shopping"),
    ("Гигиена тауарлары", "shopping"),
    ("Сыйлық сертификат", "shopping"),
    ("Аксессуарлар дүкені", "shopping"),
    ("Балаларға киім", "shopping"),
    ("Мектеп керек-жарақ", "shopping"),
    ("Жаңа телефон", "shopping"),

    # ── EDUCATION extended ────────────────────────────────────────────
    ("Платное обучение", "education"),
    ("Подготовка к ЕГЭ", "education"),
    ("ЕГЭ репетитор", "education"),
    ("IELTS подготовка", "education"),
    ("TOEFL курс", "education"),
    ("Английский онлайн", "education"),
    ("Немецкий язык курс", "education"),
    ("Испанский язык", "education"),
    ("Корейский язык", "education"),
    ("Китайский язык", "education"),
    ("Детский кружок", "education"),
    ("Шахматы секция", "education"),
    ("Рисование курс", "education"),
    ("Фотография мастер класс", "education"),
    ("Публичные выступления", "education"),
    ("IELTS preparation", "education"),
    ("Language tutoring", "education"),
    ("Math tutoring", "education"),
    ("Science course", "education"),
    ("Music lessons", "education"),
    ("Art class", "education"),
    ("Chess club fee", "education"),
    ("Swimming lessons", "education"),
    ("Coding bootcamp", "education"),
    ("Data science course", "education"),
    ("Design course", "education"),
    ("Marketing course", "education"),
    ("Finance course", "education"),
    ("Writing workshop", "education"),
    ("Public speaking class", "education"),
    ("ҰБТ дайындық", "education"),
    ("IELTS курсы", "education"),
    ("Ағылшын тілі оқу", "education"),
    ("Онлайн оқыту", "education"),
    ("Балалар үйірмесі", "education"),
    ("Музыка сабағы", "education"),
    ("Сурет салу курсы", "education"),
    ("Бағдарламалау курсы", "education"),
    ("Математика репетиторы", "education"),
    ("Тіл мектебі", "education"),

    # ── TRAVEL extended ────────────────────────────────────────────
    ("Море отдых", "travel"),
    ("Пляжный отдых", "travel"),
    ("Горный туризм", "travel"),
    ("Поход треккинг", "travel"),
    ("Сафари тур", "travel"),
    ("Медовый месяц тур", "travel"),
    ("Семейный отдых", "travel"),
    ("Детский лагерь", "travel"),
    ("Студенческий тур", "travel"),
    ("Деловая командировка", "travel"),
    ("Конференция поездка", "travel"),
    ("Визовый центр", "travel"),
    ("Загранпаспорт", "travel"),
    ("Страховка путешественника", "travel"),
    ("Трансфер отель", "travel"),
    ("Beach vacation", "travel"),
    ("Mountain hiking trip", "travel"),
    ("Honeymoon package", "travel"),
    ("Family vacation", "travel"),
    ("Business travel", "travel"),
    ("Conference trip", "travel"),
    ("Passport fee", "travel"),
    ("Travel visa application", "travel"),
    ("Road trip fuel", "travel"),
    ("Camping gear", "travel"),
    ("Snorkeling tour", "travel"),
    ("Guided tour", "travel"),
    ("Train travel Europe", "travel"),
    ("Budget airline", "travel"),
    ("Luggage fee", "travel"),
    ("Теңіз демалысы", "travel"),
    ("Тау туризмі", "travel"),
    ("Бал айы саяхаты", "travel"),
    ("Отбасылық демалыс", "travel"),
    ("Іссапар", "travel"),
    ("Виза орталығы", "travel"),
    ("Загранпаспорт алу", "travel"),
    ("Балалар лагері", "travel"),
    ("Демалыс пакеті", "travel"),
    ("Ұшу билеті сатып алу", "travel"),

    # ── TRANSFER extended ────────────────────────────────────────────
    ("Перевод маме", "transfer"),
    ("Перевод папе", "transfer"),
    ("Перевод жене", "transfer"),
    ("Перевод мужу", "transfer"),
    ("Перевод ребёнку", "transfer"),
    ("Подарок деньгами", "transfer"),
    ("Займ другу", "transfer"),
    ("Вернуть деньги", "transfer"),
    ("Оплата за ремонт", "transfer"),
    ("Задаток аренда", "transfer"),
    ("Депозит банк", "transfer"),
    ("Перевод за рубеж", "transfer"),
    ("SWIFT перевод", "transfer"),
    ("Криптовалюта перевод", "transfer"),
    ("Благотворительность", "transfer"),
    ("Transfer to mom", "transfer"),
    ("Transfer to spouse", "transfer"),
    ("Money gift", "transfer"),
    ("Loan to friend", "transfer"),
    ("Deposit transfer", "transfer"),
    ("International wire", "transfer"),
    ("SWIFT payment", "transfer"),
    ("Crypto transfer", "transfer"),
    ("Charity donation", "transfer"),
    ("Crowdfunding support", "transfer"),
    ("Peer to peer payment", "transfer"),
    ("Split bill", "transfer"),
    ("Refund transfer", "transfer"),
    ("Salary advance", "transfer"),
    ("Bonus transfer", "transfer"),
    ("Анаға аудару", "transfer"),
    ("Әкеге аудару", "transfer"),
    ("Жұбайына аудару", "transfer"),
    ("Баласына ақша", "transfer"),
    ("Сыйлық ақша", "transfer"),
    ("Халықаралық аудару", "transfer"),
    ("Қайырымдылық", "transfer"),
    ("Депозит аудару", "transfer"),
    ("Несие төлемі", "transfer"),
    ("Бөлу төлемі", "transfer"),
    # ── TRANSFER KZ extra: Kaspi + аударым маркеры ──────────────────────
    ("Kaspi аударым", "transfer"),
    ("Kaspi Gold аудару", "transfer"),
    ("Kaspi Pay аударым", "transfer"),
    ("Каспи аударым достарға", "transfer"),
    ("Каспи банк аудару", "transfer"),
    ("Халық банк аударым", "transfer"),
    ("Жинақ банк аудару", "transfer"),
    ("Forte Bank аударым", "transfer"),
    ("Достарға ақша жіберу", "transfer"),
    ("Туысқандарға аудару", "transfer"),
    ("Телефон нөмірі аударым", "transfer"),
    ("Карта нөмірі аудару", "transfer"),
    ("Онлайн аударым", "transfer"),
    ("P2P аударым", "transfer"),
    ("Борышты қайтару", "transfer"),
    ("Ақша сыйлық", "transfer"),
    ("Қол ақша бер", "transfer"),
    ("Аударым жасадым", "transfer"),
    ("Несие өтеу", "transfer"),
    ("Жалақы аванс", "transfer"),

    # ════════════════════════════════════════════════════════════════════
    # SHOPPING — усиление (F1 был 0.478, путал с food и utilities)
    # Добавляем чёткие бренды одежды, электроники, онлайн-ритейла
    # ════════════════════════════════════════════════════════════════════

    # Russian — одежда и обувь (явные маркеры)
    ("Zara платье", "shopping"),
    ("H&M куртка", "shopping"),
    ("Uniqlo одежда", "shopping"),
    ("Pull&Bear джинсы", "shopping"),
    ("Bershka кофта", "shopping"),
    ("Massimo Dutti рубашка", "shopping"),
    ("Reserved пальто", "shopping"),
    ("Адидас кроссовки магазин", "shopping"),
    ("Nike Air Force кроссовки", "shopping"),
    ("New Balance кроссовки", "shopping"),
    ("Puma магазин одежда", "shopping"),
    ("Reebok обувь магазин", "shopping"),
    ("Lacoste поло", "shopping"),
    ("Tommy Hilfiger магазин", "shopping"),
    ("Calvin Klein одежда", "shopping"),

    # Russian — электроника и техника (явные маркеры)
    ("iPhone покупка", "shopping"),
    ("MacBook магазин", "shopping"),
    ("Samsung Galaxy смартфон", "shopping"),
    ("Xiaomi телефон", "shopping"),
    ("Наушники AirPods", "shopping"),
    ("Ноутбук Lenovo", "shopping"),
    ("Планшет iPad", "shopping"),
    ("Телевизор LG", "shopping"),
    ("Холодильник Samsung", "shopping"),
    ("Стиральная машина", "shopping"),
    ("Пылесос Dyson", "shopping"),
    ("Кофемашина покупка", "shopping"),
    ("Фотоаппарат Sony", "shopping"),

    # Russian — онлайн-ритейл (явные маркеры)
    ("Wildberries одежда", "shopping"),
    ("Wildberries обувь", "shopping"),
    ("Ozon электроника", "shopping"),
    ("Ozon одежда заказ", "shopping"),
    ("Алиэкспресс товар", "shopping"),
    ("Amazon покупка", "shopping"),
    ("Lamoda заказ", "shopping"),
    ("СберМегаМаркет товар", "shopping"),
    ("Яндекс Маркет покупка", "shopping"),

    # Russian — косметика и уход (отдельно от food)
    ("MAC косметика", "shopping"),
    ("Sephora покупка", "shopping"),
    ("NYX помада", "shopping"),
    ("Кремы уход Л'Этуаль", "shopping"),
    ("Парфюм Chanel", "shopping"),
    ("Духи Dior", "shopping"),
    ("Шампунь магазин товары", "shopping"),

    # English — brands
    ("Zara clothing", "shopping"),
    ("H&M store purchase", "shopping"),
    ("ASOS order", "shopping"),
    ("Shein clothes", "shopping"),
    ("Uniqlo shirt", "shopping"),
    ("Gap jeans", "shopping"),
    ("Nike shoes store", "shopping"),
    ("Adidas sneakers store", "shopping"),
    ("Apple Store iPhone", "shopping"),
    ("Best Buy laptop", "shopping"),
    ("Samsung store phone", "shopping"),
    ("Amazon clothing", "shopping"),
    ("eBay purchase item", "shopping"),
    ("Sephora cosmetics", "shopping"),
    ("Ulta beauty", "shopping"),
    ("IKEA furniture store", "shopping"),
    ("Wayfair furniture", "shopping"),
    ("Lowe's hardware", "shopping"),
    ("Nordstrom department", "shopping"),
    ("Macy's store", "shopping"),

    # Kazakh — сатып алу (явные маркеры)
    ("Киім сатып алу", "shopping"),
    ("Аяқ киім дүкені", "shopping"),
    ("Смартфон сатып алу", "shopping"),
    ("Ноутбук сатып алу", "shopping"),
    ("Онлайн тапсырыс киім", "shopping"),
    ("Wildberries киім", "shopping"),
    ("Ozon тапсырыс", "shopping"),
    ("Косметика дүкені", "shopping"),
    ("Жиһаз дүкені", "shopping"),
    ("Электроника дүкені", "shopping"),
    ("Спорт киімі", "shopping"),
    ("Балалар киімі дүкені", "shopping"),
    ("Сағат сатып алу", "shopping"),
    ("Сөмке дүкені", "shopping"),
    ("Кітап сатып алу", "shopping"),

    # ════════════════════════════════════════════════════════════════════
    # CODE-SWITCHING — смешанные KZ+RU и KZ+EN фразы
    # Реальный паттерн казахских пользователей: бренд/сервис на RU/EN,
    # категорийное слово — на KZ
    # ════════════════════════════════════════════════════════════════════

    # food (code-switching)
    ("Магнит азық-түлік", "food"),
    ("Пятёрочка азық", "food"),
    ("Ашан дүкені азық", "food"),
    ("Metro Cash азық-түлік", "food"),
    ("Supermarket азық", "food"),
    ("Дикси нан сүт", "food"),
    ("Glovo азық жеткізу", "food"),
    ("Яндекс Лавка азық", "food"),
    ("Small shop азық", "food"),
    ("Market азық-түлік алу", "food"),

    # cafe (code-switching)
    ("Starbucks кофе алу", "cafe"),
    ("KFC тамақ", "cafe"),
    ("McDonald's жеу", "cafe"),
    ("Burger King тамақтану", "cafe"),
    ("Pizza Hut тапсырыс", "cafe"),
    ("Dodo Pizza жеткізу", "cafe"),
    ("Domino's пицца", "cafe"),
    ("Glovo тамақ жеткізу", "cafe"),
    ("Yandex Food тапсырыс", "cafe"),
    ("Wolt мейрамхана", "cafe"),
    ("Chili's ресторан", "cafe"),
    ("Coffee House кофе", "cafe"),

    # transport (code-switching)
    ("Яндекс такси жолдама", "transport"),
    ("Uber жолдама", "transport"),
    ("Bolt такси", "transport"),
    ("InDrive жол", "transport"),
    ("Yandex Go жолдама", "transport"),
    ("Яндекс Go поездка KZ", "transport"),
    ("Метро билет алу", "transport"),
    ("Bus card толтыру", "transport"),
    ("Avtovokzal билет", "transport"),
    ("Kaspi такси", "transport"),

    # health (code-switching)
    ("Apteka дәрі", "health"),
    ("Daribar дәрілер", "health"),
    ("Медцентр клиника", "health"),
    ("Online doctor консультация", "health"),
    ("Lab анализ", "health"),
    ("Dentist стоматолог", "health"),
    ("Gym абонемент", "health"),
    ("Fitness club жазылым", "health"),
    ("Медикамент дәріхана", "health"),

    # entertainment (code-switching)
    ("Netflix жазылым", "entertainment"),
    ("Spotify музыка", "entertainment"),
    ("YouTube Premium KZ", "entertainment"),
    ("Steam ойын сатып алу", "entertainment"),
    ("Кино билет онлайн", "entertainment"),
    ("Ticketon концерт", "entertainment"),
    ("Play Market ойын", "entertainment"),
    ("App Store жазылым", "entertainment"),
    ("Кинотеатр билеті", "entertainment"),
    ("Online кино көру", "entertainment"),

    # utilities (code-switching)
    ("Коммуналдық Kcell шот", "utilities"),
    ("Beeline интернет шот", "utilities"),
    ("Activ телефон шот", "utilities"),
    ("Казахтелеком интернет", "utilities"),
    ("ЕСЖК коммуналдық", "utilities"),
    ("Электр шот", "utilities"),
    ("Газ шот төлем", "utilities"),
    ("Алматы жылу шот", "utilities"),
    ("Тұрмыстық шот", "utilities"),

    # shopping (code-switching)
    ("Wildberries тапсырыс KZ", "shopping"),
    ("Kaspi Shop сатып алу", "shopping"),
    ("Ozon тапсырыс KZ", "shopping"),
    ("AliExpress тапсырыс", "shopping"),
    ("Lamoda киім", "shopping"),
    ("Adidas дүкені KZ", "shopping"),
    ("Zara киім сатып алу", "shopping"),
    ("H&M дүкені", "shopping"),
    ("Samsung телефон сатып алу", "shopping"),
    ("Apple Store KZ", "shopping"),
    ("Nike кроссовки KZ", "shopping"),
    ("Sulpak электроника", "shopping"),
    ("Technodom ноутбук", "shopping"),
    ("Mechta дүкен", "shopping"),

    # education (code-switching)
    ("Coursera курс KZ", "education"),
    ("Udemy сертификат", "education"),
    ("Skyeng ағылшын", "education"),
    ("Duolingo Premium KZ", "education"),
    ("ЕНТ дайындық курс", "education"),
    ("Online мектеп жазылым", "education"),
    ("Университет оқу ақысы", "education"),
    ("Репетитор математика", "education"),

    # travel (code-switching)
    ("Air Astana билет", "travel"),
    ("FlyArystan ұшу", "travel"),
    ("Kaspi Travel брондау", "travel"),
    ("Booking отель", "travel"),
    ("Airbnb тұру", "travel"),
    ("Aviasales билет", "travel"),
    ("Otель брондау KZ", "travel"),
    ("Поезд Алматы Астана билет", "travel"),
    ("Экскурсия тур", "travel"),

    # transfer (code-switching)
    ("Kaspi аударым достарға", "transfer"),
    ("Halyk Bank аудару", "transfer"),
    ("Сбербанк перевод KZ", "transfer"),
    ("PayPal аудару", "transfer"),
    ("Western Union аударым", "transfer"),
    ("Қарыз қайтару Kaspi", "transfer"),
    ("Kaspi Gold аударым жіберу", "transfer"),
    ("Ақша жіберу онлайн", "transfer"),
    ("Card-to-card аударым", "transfer"),
    ("Жолдасқа ақша беру", "transfer"),
]

CATEGORIES = [
    "food", "cafe", "transport", "health",
    "entertainment", "utilities", "shopping",
    "education", "travel", "transfer"
]

CATEGORY_LABELS_RU = {
    "food": "Продукты",
    "cafe": "Кафе и рестораны",
    "transport": "Транспорт",
    "health": "Здоровье",
    "entertainment": "Развлечения",
    "utilities": "Коммунальные услуги",
    "shopping": "Покупки",
    "education": "Образование",
    "travel": "Путешествия",
    "transfer": "Переводы",
}

CATEGORY_LABELS_KZ = {
    "food": "Азық-түлік",
    "cafe": "Мейрамханалар",
    "transport": "Көлік",
    "health": "Денсаулық",
    "entertainment": "Ойын-сауық",
    "utilities": "Коммуналдық қызметтер",
    "shopping": "Сатып алу",
    "education": "Білім",
    "travel": "Саяхат",
    "transfer": "Аударым",
}
