apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scheduler-worker.fullname" . }}
  labels: {{- include "scheduler-worker.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
