apiVersion: v2
name: user-service
description: AIFA user-service — profile management
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://aifa.app/icon.png
keywords:
  - aifa
  - user
  - microservice
maintainers:
  - name: sur1cat
    email: sur1cat@users.noreply.github.com
