apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task-service.fullname" . }}
  labels: {{- include "task-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.targetPort | quote }}
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
